spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smartbilling
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create   # Crea/actualiza automáticamente las tablas según tus entidades Java
    show-sql: true       # Muestra en consola las queries SQL que se ejecutan
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080             # Puerto donde correrá la aplicación Spring Boot